- name: Create the pihole container
  become_user: '{{ ansible_ssh_user }}'
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "8088:80/"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "/home/{{ ansible_ssh_user }}/etc-pihole:/etc/pihole"
      - "/home/{{ ansible_ssh_user }}/etc-dnsmasq.d:/etc/dnsmasq.d"
    env:
      TZ: Europe/Paris
      VIRTUAL_HOST: pi.hole
      PROXY_LOCATION: pi.hole
      FTLCONF_LOCAL_IPV4: 127.0.0.1
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEBPASSWORD: "{{ PIHOLE_WEBPASSWORD }}"
    restart_policy: always
